export const NAC = [
  "United States of America",
  "Canada",
  "Mexico",
  "Antigua and Barbuda",
  "Bahamas",
  "Barbados",
  "Cuba",
  "Dominica",
  "Dominican Republic",
  "Grenada",
  "Haiti",
  "Jamaica",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Trinidad and Tobago",
];

export const WNS = [
  "Austria",
  "Belgium",
  "France",
  "Germany",
  "Ireland",
  "Sweden",
  "Finland",
  "Norway",
  "Liechtenstein",
  "Luxembourg",
  "Monaco",
  "Netherlands",
  "Switzerland",
  "United Kingdom",
];

export const Oceania = [
  "Australia",
  "New Zealand",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Cambodia",
  "Myanmar",
  "Laos",
  "Vietnam",
  "Malaysia",
  "Fiji",
  "Papua New Guinea",
  "Solomon Islands",
  "Vanuata",
  "Federated States of Micronesia",
  "Kiribati",
  "Marshall Islands",
  "Nauru",
  "Palau",
  "Samoa",
  "Tonga",
  "Tuvalu",
  "French Polynesia",
  "New Caledonia",
  "Wallis and Futuna",
  "American Samoa",
  "Guam",
  "Northern Mariana Islands",
  "Cook Islands",
  "Niue",
  "Tokelau",
  "Pitcairn Islands",
];

export const SSA = [
  "Benin",
  "Burkina Faso",
  ,
  "Botswana",
  "Burundi",
  "Cape Verde",
  "Comoros",
  "Côte d'Ivoire",
  "Dem. Rep. Congo",
  "Djibouti",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Equatorial Guinea",
  "Eritrea",
  "Kenya",
  "Lesotho",
  "liberia",
  "Madagascar",
  "Malawi",
  "eSwatini",
  "Mozambique",
  "Namibia",
  "Rwanda",
  "São Tomé and Príncipe",
  "Seychelles",
  "Somalia",
  "South Africa",
  "S. Sudan",
  "Tanzania",
  "Uganda",
  "Zambia",
  "Zimbabwe",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Liberia",
  "Mali",
  "Mauritania",
  "Niger",
  "Nigeria",
  "Senegal",
  "Sierra Leone",
  "Togo",
  "Angola",
  "Cameroon",
  "Central African Rep.",
  "Chad",
  "Congo",
];

export const LAC = [
  "Belize",
  "Costa Rica",
  "El Salvador",
  "Guatemala",
  "Honduras",
  "Nicaragua",
  "Panama",
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Guyana",
  "Paraguay",
  "Peru",
  "Suriname",
  "Uruguay",
  "Venezuela",
  "Antigua and Barbuda",
  "Bahamas",
  "Barbados",
  "Cuba",
  "Dominica",
  "Dominican Republic",
  "Grenada",
  "Haiti",
  "Jamaica",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Trinidad and Tobago",
];

export const SA = [
  "Afghanistan",
  "Bhutan",
  "Bangladesh",
  "India",
  "Maldives",
  "Nepal",
  "Pakistan",
  "Sri Lanka",
];

export const ESE = [
  "Bulgaria",
  "Czech Republic",
  "Hungary",

  "Poland",
  "Romania",

  "Slovakia",

  "Albania",
  "Bosnia and Herzegovina",
  "Croatia",
  "Greece",
  "Kosovo",
  "Montenegro",
  "North Macedonia",
  "Serbia",
  "Slovenia",
];

export const MENA = [
  "Algeria",
  "Egypt",
  "Libya",
  "Morocco",
  "Sudan",
  "Tunisia",
  "Bahrain",
  "Cyprus",
  "Iran",
  "Iraq",
  "Israel",
  "Jordan",
  "Kuwait",
  "Lebanon",
  "Oman",
  "Palestine",
  "Qatar",
  "Saudi Arabia",
  "Syria",
  "Turkey",
  "United Arab Emirates",
  "Yemen",
];

export const EEC = [
  "Belarus",
  "Russia",
  "Ukraine",
  "Moldova",
  "Armenia",
  "Azerbaijan",
  "Georgia",
  "Kazakhstan",
  "Kyrgyzstan",
  "Tajikistan",
  "Turkmenistan",
  "Uzbekistan",
];
